// <auto-generated />
using System;
using Device.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Device.EntityFramework.Migrations
{
    [DbContext(typeof(DeviceDbContext))]
    [Migration("20220318012425_Seed_Tbl_Devices")]
    partial class Seed_Tbl_Devices
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Device.Domain.Device.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7c00b09f-4562-4e2f-b95d-edd6e2240b96"),
                            CreationTime = new DateTime(2022, 3, 17, 8, 31, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Work Smartphone",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("98ec6ea5-d591-47f3-9f36-c1c9f2a3316c"),
                            CreationTime = new DateTime(2022, 3, 17, 10, 23, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Son Ipad",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("0e05ba9d-a84f-48da-bd1d-19eaabfe1590"),
                            CreationTime = new DateTime(2022, 3, 18, 9, 4, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Home Laptop",
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("b2780a57-cce2-4244-9c28-5cee4c04f6b7"),
                            CreationTime = new DateTime(2022, 3, 19, 11, 38, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Work Server",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("6cd66acb-33c5-43a4-8987-5ef566ed524c"),
                            CreationTime = new DateTime(2022, 3, 19, 15, 38, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "School Desktop",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("7fa37ac2-9edf-469f-8d2a-535aab49b00e"),
                            CreationTime = new DateTime(2022, 3, 19, 17, 38, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Hall Television",
                            Type = 6
                        },
                        new
                        {
                            Id = new Guid("4274be17-8e8e-4012-8be4-978579607f3a"),
                            CreationTime = new DateTime(2022, 3, 20, 10, 23, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Mom Ipad",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("46c2ae34-db80-40d1-ac73-d9b01eaf511c"),
                            CreationTime = new DateTime(2022, 3, 21, 9, 4, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Daughter Laptop",
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("edd25796-460b-4da4-8340-4a283024d506"),
                            CreationTime = new DateTime(2022, 3, 21, 11, 38, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Bedroom TV",
                            Type = 6
                        },
                        new
                        {
                            Id = new Guid("9bea121f-ae8e-4db3-b433-419596e573eb"),
                            CreationTime = new DateTime(2022, 3, 23, 15, 38, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Mom Smartphone",
                            Type = 0
                        });
                });

            modelBuilder.Entity("Device.Domain.Device.Entities.DeviceDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<float>("Temperature")
                        .HasColumnType("real");

                    b.Property<float>("Usage")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("DeviceDetails");
                });

            modelBuilder.Entity("Device.Domain.Device.Entities.DeviceDetails", b =>
                {
                    b.HasOne("Device.Domain.Device.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
