// <auto-generated />
using System;
using Device.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Device.EntityFramework.Migrations
{
    [DbContext(typeof(DeviceDbContext))]
    [Migration("20220323023343_Seed_Tbl_DeviceDetails")]
    partial class Seed_Tbl_DeviceDetails
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Device.Domain.Device.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7c00b09f-4562-4e2f-b95d-edd6e2240b96"),
                            CreationTime = new DateTime(2022, 3, 17, 8, 31, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Work Smartphone",
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("98ec6ea5-d591-47f3-9f36-c1c9f2a3316c"),
                            CreationTime = new DateTime(2022, 3, 17, 10, 23, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Son Ipad",
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("0e05ba9d-a84f-48da-bd1d-19eaabfe1590"),
                            CreationTime = new DateTime(2022, 3, 18, 9, 4, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Home Laptop",
                            Status = 0,
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("7fa37ac2-9edf-469f-8d2a-535aab49b00e"),
                            CreationTime = new DateTime(2022, 3, 19, 17, 38, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Hall Television",
                            Status = 0,
                            Type = 6
                        },
                        new
                        {
                            Id = new Guid("b2780a57-cce2-4244-9c28-5cee4c04f6b7"),
                            CreationTime = new DateTime(2022, 3, 19, 11, 38, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Work Server",
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("edd25796-460b-4da4-8340-4a283024d506"),
                            CreationTime = new DateTime(2022, 3, 21, 11, 38, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Bedroom TV",
                            Status = 0,
                            Type = 6
                        },
                        new
                        {
                            Id = new Guid("9bea121f-ae8e-4db3-b433-419596e573eb"),
                            CreationTime = new DateTime(2022, 3, 22, 15, 38, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Mom Smartphone",
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("5b9eda9d-d878-4b6d-b041-11e725bcccd4"),
                            CreationTime = new DateTime(2022, 3, 19, 11, 38, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Work Hall Desktop",
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("cde3b44e-9603-4fc4-89b4-a027c3aab5eb"),
                            CreationTime = new DateTime(2022, 3, 21, 11, 38, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Work Hall TV",
                            Status = 0,
                            Type = 6
                        },
                        new
                        {
                            Id = new Guid("8f458b6f-40d7-48ac-9277-6727c45cfd22"),
                            CreationTime = new DateTime(2022, 3, 22, 15, 38, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Work Smartphone",
                            Status = 0,
                            Type = 0
                        });
                });

            modelBuilder.Entity("Device.Domain.Device.Entities.DeviceDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<float>("Temperature")
                        .HasColumnType("real");

                    b.Property<float>("Usage")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("DeviceDetails");

                    b.HasData(
                        new
                        {
                            Id = new Guid("39c77279-fa83-493d-8581-e1771c7d7c1e"),
                            CreationTime = new DateTime(2022, 3, 23, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = new Guid("7c00b09f-4562-4e2f-b95d-edd6e2240b96"),
                            IsDeleted = false,
                            Temperature = 30.458f,
                            Usage = 5437547f
                        },
                        new
                        {
                            Id = new Guid("f51b1e84-71af-4987-b649-29d35cc8ac7b"),
                            CreationTime = new DateTime(2022, 3, 23, 8, 40, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = new Guid("7c00b09f-4562-4e2f-b95d-edd6e2240b96"),
                            IsDeleted = false,
                            Temperature = 28.458f,
                            Usage = 5423818f
                        },
                        new
                        {
                            Id = new Guid("15096be5-4434-4622-bcc7-79ac960be0c9"),
                            CreationTime = new DateTime(2022, 3, 23, 8, 50, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = new Guid("7c00b09f-4562-4e2f-b95d-edd6e2240b96"),
                            IsDeleted = false,
                            Temperature = 32.5458f,
                            Usage = 7564754f
                        },
                        new
                        {
                            Id = new Guid("9f2d9e79-c201-428e-bb50-ec9afe7bfa25"),
                            CreationTime = new DateTime(2022, 3, 23, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = new Guid("98ec6ea5-d591-47f3-9f36-c1c9f2a3316c"),
                            IsDeleted = false,
                            Temperature = 29.4458f,
                            Usage = 236525f
                        },
                        new
                        {
                            Id = new Guid("99ac592a-5123-4a63-94a1-cd161153d79e"),
                            CreationTime = new DateTime(2022, 3, 23, 8, 40, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = new Guid("98ec6ea5-d591-47f3-9f36-c1c9f2a3316c"),
                            IsDeleted = false,
                            Temperature = 34.5658f,
                            Usage = 52346248f
                        },
                        new
                        {
                            Id = new Guid("fa73f6c9-fe68-4e18-bf8b-c17ad8fa9373"),
                            CreationTime = new DateTime(2022, 3, 23, 8, 50, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = new Guid("98ec6ea5-d591-47f3-9f36-c1c9f2a3316c"),
                            IsDeleted = false,
                            Temperature = 35.458f,
                            Usage = 6345532f
                        },
                        new
                        {
                            Id = new Guid("d4419940-6f1a-48fd-9499-79594f20cb9a"),
                            CreationTime = new DateTime(2022, 3, 23, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = new Guid("0e05ba9d-a84f-48da-bd1d-19eaabfe1590"),
                            IsDeleted = false,
                            Temperature = 31.458f,
                            Usage = 262623f
                        },
                        new
                        {
                            Id = new Guid("b22769e6-efb1-4502-8d1e-6568db4dbd1f"),
                            CreationTime = new DateTime(2022, 3, 23, 8, 40, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = new Guid("0e05ba9d-a84f-48da-bd1d-19eaabfe1590"),
                            IsDeleted = false,
                            Temperature = 28.458f,
                            Usage = 145125f
                        },
                        new
                        {
                            Id = new Guid("37d22d4d-23c0-41ca-91a5-072a70da5d83"),
                            CreationTime = new DateTime(2022, 3, 23, 8, 50, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = new Guid("0e05ba9d-a84f-48da-bd1d-19eaabfe1590"),
                            IsDeleted = false,
                            Temperature = 30.458f,
                            Usage = 43633f
                        },
                        new
                        {
                            Id = new Guid("c9f95416-8cd0-4e0c-a73f-de52c9be2d89"),
                            CreationTime = new DateTime(2022, 3, 23, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = new Guid("7fa37ac2-9edf-469f-8d2a-535aab49b00e"),
                            IsDeleted = false,
                            Temperature = 31.458f,
                            Usage = 367357f
                        },
                        new
                        {
                            Id = new Guid("18029775-3e1c-4d5f-8f09-1b10cf7eb6ed"),
                            CreationTime = new DateTime(2022, 3, 23, 8, 40, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = new Guid("7fa37ac2-9edf-469f-8d2a-535aab49b00e"),
                            IsDeleted = false,
                            Temperature = 32.38f,
                            Usage = 7363445f
                        },
                        new
                        {
                            Id = new Guid("40539503-7919-4f68-892a-e010918df244"),
                            CreationTime = new DateTime(2022, 3, 23, 8, 50, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = new Guid("7fa37ac2-9edf-469f-8d2a-535aab49b00e"),
                            IsDeleted = false,
                            Temperature = 30.458f,
                            Usage = 2652355f
                        },
                        new
                        {
                            Id = new Guid("5e600eb4-597b-40a4-a5f6-6b44b90b6ef2"),
                            CreationTime = new DateTime(2022, 3, 23, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = new Guid("b2780a57-cce2-4244-9c28-5cee4c04f6b7"),
                            IsDeleted = false,
                            Temperature = 29.458f,
                            Usage = 451552f
                        },
                        new
                        {
                            Id = new Guid("cf9f402f-2ba1-4080-a674-14ad0eea9824"),
                            CreationTime = new DateTime(2022, 3, 23, 8, 40, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = new Guid("b2780a57-cce2-4244-9c28-5cee4c04f6b7"),
                            IsDeleted = false,
                            Temperature = 30.658f,
                            Usage = 2352352f
                        },
                        new
                        {
                            Id = new Guid("4f80e15a-b2af-4f86-b403-000218729525"),
                            CreationTime = new DateTime(2022, 3, 23, 8, 50, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = new Guid("b2780a57-cce2-4244-9c28-5cee4c04f6b7"),
                            IsDeleted = false,
                            Temperature = 30.748f,
                            Usage = 32532524f
                        },
                        new
                        {
                            Id = new Guid("b2d11652-c5e5-4093-93e6-ff8ed032c95f"),
                            CreationTime = new DateTime(2022, 3, 23, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = new Guid("edd25796-460b-4da4-8340-4a283024d506"),
                            IsDeleted = false,
                            Temperature = 30.458f,
                            Usage = 451552f
                        },
                        new
                        {
                            Id = new Guid("6793f594-aeff-4e9d-8b34-05968f732de7"),
                            CreationTime = new DateTime(2022, 3, 23, 8, 40, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = new Guid("edd25796-460b-4da4-8340-4a283024d506"),
                            IsDeleted = false,
                            Temperature = 33.458f,
                            Usage = 235235f
                        },
                        new
                        {
                            Id = new Guid("21ad706c-08bb-406d-bb7f-33890b908462"),
                            CreationTime = new DateTime(2022, 3, 23, 8, 50, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = new Guid("edd25796-460b-4da4-8340-4a283024d506"),
                            IsDeleted = false,
                            Temperature = 30.358f,
                            Usage = 23523f
                        },
                        new
                        {
                            Id = new Guid("620fb4d1-bb9e-479a-8583-655aefc13265"),
                            CreationTime = new DateTime(2022, 3, 23, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = new Guid("9bea121f-ae8e-4db3-b433-419596e573eb"),
                            IsDeleted = false,
                            Temperature = 30.458f,
                            Usage = 3463443f
                        },
                        new
                        {
                            Id = new Guid("07865b3b-5559-4246-937f-46661f694361"),
                            CreationTime = new DateTime(2022, 3, 23, 8, 40, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = new Guid("9bea121f-ae8e-4db3-b433-419596e573eb"),
                            IsDeleted = false,
                            Temperature = 32.458f,
                            Usage = 321532f
                        },
                        new
                        {
                            Id = new Guid("85ae8097-a6bb-4933-9adb-2114f11c6c29"),
                            CreationTime = new DateTime(2022, 3, 23, 8, 50, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = new Guid("9bea121f-ae8e-4db3-b433-419596e573eb"),
                            IsDeleted = false,
                            Temperature = 31.98f,
                            Usage = 23523524f
                        },
                        new
                        {
                            Id = new Guid("f5aa9b1a-370f-4a80-9a22-8ebe49722258"),
                            CreationTime = new DateTime(2022, 3, 23, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = new Guid("5b9eda9d-d878-4b6d-b041-11e725bcccd4"),
                            IsDeleted = false,
                            Temperature = 30.458f,
                            Usage = 3463443f
                        },
                        new
                        {
                            Id = new Guid("ee482c35-de11-4030-9515-323500db08de"),
                            CreationTime = new DateTime(2022, 3, 23, 8, 40, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = new Guid("5b9eda9d-d878-4b6d-b041-11e725bcccd4"),
                            IsDeleted = false,
                            Temperature = 32.458f,
                            Usage = 321532f
                        },
                        new
                        {
                            Id = new Guid("993ae2c5-5495-4abe-98ec-12c6ecc9bbc1"),
                            CreationTime = new DateTime(2022, 3, 23, 8, 50, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = new Guid("5b9eda9d-d878-4b6d-b041-11e725bcccd4"),
                            IsDeleted = false,
                            Temperature = 31.98f,
                            Usage = 23523524f
                        },
                        new
                        {
                            Id = new Guid("69b50dc5-4fa5-4056-8280-e0c615988df3"),
                            CreationTime = new DateTime(2022, 3, 23, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = new Guid("cde3b44e-9603-4fc4-89b4-a027c3aab5eb"),
                            IsDeleted = false,
                            Temperature = 30.458f,
                            Usage = 3463443f
                        },
                        new
                        {
                            Id = new Guid("14b782bc-ce4f-4600-b75d-fce170dc2333"),
                            CreationTime = new DateTime(2022, 3, 23, 8, 40, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = new Guid("cde3b44e-9603-4fc4-89b4-a027c3aab5eb"),
                            IsDeleted = false,
                            Temperature = 32.458f,
                            Usage = 321532f
                        },
                        new
                        {
                            Id = new Guid("8eb6a5be-86f6-4760-bf2e-b1e2ee3ac50b"),
                            CreationTime = new DateTime(2022, 3, 23, 8, 50, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = new Guid("cde3b44e-9603-4fc4-89b4-a027c3aab5eb"),
                            IsDeleted = false,
                            Temperature = 31.98f,
                            Usage = 23523524f
                        },
                        new
                        {
                            Id = new Guid("f27deca6-efc1-49dc-85e6-48ecac1dcd82"),
                            CreationTime = new DateTime(2022, 3, 23, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = new Guid("8f458b6f-40d7-48ac-9277-6727c45cfd22"),
                            IsDeleted = false,
                            Temperature = 30.458f,
                            Usage = 3463443f
                        },
                        new
                        {
                            Id = new Guid("cde4793b-6af4-4aad-91b6-3eae2bf347c2"),
                            CreationTime = new DateTime(2022, 3, 23, 8, 40, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = new Guid("8f458b6f-40d7-48ac-9277-6727c45cfd22"),
                            IsDeleted = false,
                            Temperature = 32.458f,
                            Usage = 321532f
                        },
                        new
                        {
                            Id = new Guid("d574f9d8-47ae-4e6b-8d2d-355e9cf63016"),
                            CreationTime = new DateTime(2022, 3, 23, 8, 50, 0, 0, DateTimeKind.Unspecified),
                            DeviceId = new Guid("8f458b6f-40d7-48ac-9277-6727c45cfd22"),
                            IsDeleted = false,
                            Temperature = 31.98f,
                            Usage = 23523524f
                        });
                });

            modelBuilder.Entity("Device.Domain.Device.Entities.DeviceDetails", b =>
                {
                    b.HasOne("Device.Domain.Device.Entities.Device", "Device")
                        .WithMany("DeviceDetails")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
